# Generated by Django 4.1.3 on 2022-11-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicule_marque', models.CharField(max_length=100)),
                ('vehicule_model', models.CharField(max_length=100)),
                ('vehicule_titre', models.CharField(max_length=100)),
                ('nombre_passager', models.CharField(max_length=10)),
                ('nombre_baguage', models.CharField(max_length=10)),
                ('vehicuile_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
