# Generated by Django 4.1.3 on 2022-11-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_image', models.ImageField(upload_to='')),
                ('service_desc', models.TextField(max_length=1000)),
            ],
        ),
    ]
